server:
    #    address: 0.0.0.0
    port: 19111
spring:
    application:
        name: '@project.artifactId@'
    jackson:
        property-naming-strategy: SNAKE_CASE
    cloud:
        gateway:
            routes:
                -   id: dvc-service
                    uri: lb://dvc-service
                    predicates:
                        - Path=/dvc-service/**
                -   id: DEPARTMENT-SERVICE
                    uri: lb://DEPARTMENT-SERVICE
                    predicates:
                        - Path=/departments/**
    security:
        user:
            name: huynv1
            password: 123456
    zipkin:
        enabled: false
eureka:
    client:
        fetch-registry: false
        healthcheck:
            enabled: true
        register-with-eureka: false
        service-url:
            defaultZone: ${EUREKA_REGISTRY_SERVICE:http://huynv1:123456@localhost:19111/eureka}
    server:
        enable-self-preservation: false
        eviction-interval-timer-in-ms: 2000
        expected-client-renewal-interval-seconds: 3
        response-cache-update-interval-ms: 5000
management:
    endpoints:
        web:
            exposure:
                include: '*'
info:
    run:
        dir: ${user.dir}
        user: ${user.name}
logging:
    level:
        org:
            springframework:
                web: DEBUG
                web.HttpLogging: INFO
        com.netflix.eureka.registry.AbstractInstanceRegistry: ERROR





