server:
    #    address: 0.0.0.0
    port: 19251
spring:
    application:
        name: '@project.artifactId@'
    jackson:
        property-naming-strategy: SNAKE_CASE
        default-property-inclusion: always
    sleuth:
        sampler:
            probability: 1
    zipkin:
        base-url: ${ZIPKIN_SERVICE:http://10.36.126.15:9411/}
    datasource:
        driver-class-name: oracle.jdbc.driver.OracleDriver
        hikari:
            connection-timeout: 60000
            maximum-pool-size: 10
        password: user_esb12
        url: jdbc:oracle:thin:@10.36.126.36:1521/EBDB
        username: USER_ESB
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.Oracle10gDialect
eureka:
    client:
        fetchRegistry: true
        registerWithEureka: true
        registryFetchIntervalSeconds: 15
        service-url:
            defaultZone: ${EUREKA_REGISTRY_SERVICE:http://huynv1:123456@localhost:19111/eureka}
    instance:
        lease-expiration-duration-in-seconds: 5
        lease-renewal-interval-in-seconds: 2
        preferIpAddress: true
info:
    run:
        dir: ${user.dir}
        user: ${user.name}
logging:
    level:
        org:
            springframework:
                data:
                    mongodb:
                        core:
                            MongoTemplate: DEBUG
                web: DEBUG
                web.HttpLogging: INFO
                web.filter.CommonsRequestLoggingFilter: DEBUG
            hibernate:
                SQL: DEBUG
                type:
                    descriptor:
                        sql:
                            BasicBinder: TRACE
management:
    endpoints:
        web:
            exposure:
                include: '*'
ribbon:
    eureka:
        enabled: true
configDbCore:
    className: oracle.jdbc.driver.OracleDriver
    urlDB: jdbc:oracle:thin:@10.36.126.45:1521/coredev
    userDB: lvbhost
    passwordDB: host4dev1
    checkDb: true


services:
    zookeeper-1:
        image: confluence/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 22181:2181

    zookeeper-2:
        image: confluence/cp-zookeeper:latest
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
        ports:
            - 32181:2181

    kafka-1:
        image: confluence/cp-kafka:latest
        depends_on:
            - zookeeper-1
            - zookeeper-2

        ports:
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-1:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    kafka-2:
        image: confluence/cp-kafka:latest
        depends_on:
            - zookeeper-1
            - zookeeper-2
        ports:
            - 39092:39092
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper-1:2181,zookeeper-2:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka-2:9092,PLAINTEXT_HOST://localhost:39092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
